### ISSUE TITLE
storagePrefix not working when useState = true

### ISSUE THREAD

**Issue by sekowalczyk** [DarylBuckle/react-oauth2-authcode-provider#5]
FYI - using storagePrefix is not working when useState = true.  

It looks like the doAuthorizationCodeFlow processing in AuthCodeFunctions.tsx is not propagating the storagePrefix value in the getCodeLocation call so the state is being saved without the storagePrefix.  This causes a 'State does not match' error in tradeCodeForToken in AuthCodeProvider.tsx since it's looking for the value with the storagePrefix.

Let me know if you need more details.

**Comment by DarylBuckle** [comment]
Hi @sekowalczyk, thanks for the info and for looking into.

I've recreated the issue and will fix in 0.1.4.
